vim.cmd("source ~/.config/nvim/startup.vim")
require("josej.plugins-setup")
require("josej.core.keymaps")
require("josej.plugins.comment")
require("josej.plugins.nvim-tree")
require("josej.plugins.lualine")
require("josej.plugins.nvim-cmp")
require("josej.plugins.lsp.mason")
require("josej.plugins.lsp.lspconfig")
require("josej.plugins.lsp.lspsaga")
require("josej.plugins.lsp.null-ls")
require("josej.plugins.autopairs")
require("josej.plugins.autotag")
require("josej.plugins.treesitter")
require("josej.plugins.gitsigns")
require("josej.plugins.barbeque")
-- require("josej.plugins.transparent")
require("josej.plugins.dressing")
require("josej.core.colorscheme")
require("josej.core.options")
