vim.cmd("source C:/configs/nvim/startup.vim")
require("christphralden.plugins-setup")
require("christphralden.core.keymaps")
require("christphralden.plugins.comment")
require("christphralden.plugins.nvim-tree")
require("christphralden.plugins.lualine")
require("christphralden.plugins.nvim-cmp")
require("christphralden.plugins.lsp.mason")
require("christphralden.plugins.lsp.lspconfig")
require("christphralden.plugins.lsp.lspsaga")
require("christphralden.plugins.lsp.null-ls")
require("christphralden.plugins.autopairs")
require("christphralden.plugins.autotag")
require("christphralden.plugins.treesitter")
require("christphralden.plugins.gitsigns")
require("christphralden.plugins.barbeque")
require("christphralden.plugins.transparent")
require("christphralden.plugins.transparent")
require("christphralden.plugins.dressing")
-- require("christphralden.core.colorscheme")
require("christphralden.core.options")
